---
# Playbook zur Konfiguration von Backbone Servern 

- hosts: backbone
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: ip_forwarding, tags: "ip_forwarding"}
    - { role: tunearpcache, tags: "tunearpcache"}
    - { role: interfaces_ffrl, tags: "interfaces_ffrl"}
    - { role: interfaces_ffms_backbone, tags: "interfaces_ffms_backbone"}
    - { role: interfaces_ffms_interbackbone, tags: "interfaces_ffms_interbackbone"}
    - { role: bird_backbone, tags: "bird_backbone"}
    - { role: collectd, tags: "collectd"}

