---
# Playbook zur Konfiguration von Backbone Servern 

- hosts: backbone
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: backports-kernel, tags: "backports-kernel"}
    - { role: ip_forwarding, tags: "ip_forwarding"}
    - { role: tunearpcache, tags: "tunearpcache"}
    - { role: net_netfilter, tags: "net_netfilter"}
    - { role: iptables, tags: "iptables"}
    - { role: backbone_gre_ffrl, tags: "backbone_gre_ffrl"}
    - { role: backbone_gre_ffms, tags: "backbon_gre_ffms"}
    - { role: bird_backbone, tags: "bird_backbone"}
    - { role: bind_backbone, tags: "bind_backbone"}
    - { role: collectd, tags: "collectd"}

