---
# Playbook zur Konfiguration aller Servern von domaene-08
# Aufruf einer einzelnen Rolle möglich. Beispiel nur fastd: "ansible-playbook domaene-08.yml --tags=fastd"

- hosts: domaene-08
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: fastd, tags: "fastd"}
    - { role: interfaces_batman, tags: "interfaces_batman"}
    - { role: interfaces_gretap, tags: "interfaces_gretap"}
    - { role: dhcp, tags: "dhcp"}
    - { role: bind_gateway, tags: "bind_gateway"}
    - { role: bird_supernodes, tags: "bird_supernodes"}
    - { role: backports-kernel, tags: "backports-kernel"}
    - { role: interfaces_ffms_supernodes, tags: "interfaces_ffms_supernodes"}
    - { role: ip_forwarding, tags: "ip_forwarding"}
    - { role: collectd, tags: "collectd"}

