---
- hosts: firmwareserver
  vars_files:
    - fastd_keys.yml
  remote_user: root
  roles:
   - { role: hostname, tags: "hostname"}
   - { role: common, tags: "common"}
   - { role: motd, tags: "motd"}
   - { role: fail2ban, tags: "fail2ban"}
   - { role: firmware_web, tags: "firmware_web", when: "'is_firmwareserver' in hostvars[inventory_hostname] and is_firmwareserver"}
   - { role: firmware_build, tags: "firmware_build", when: "'is_buildserver' in hostvars[inventory_hostname] and is_buildserver"}
#   - { role: firmware_nginx, tags: "firmware_nginx"} # NOCH BAUSTELLE!
   - { role: collectd, tags: "collectd"}
