---
- hosts: gateways 
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: backports-kernel, tags: "backports-kernel"}
    - { role: net_netfilter, tags: "net_netfilter"}
    - { role: tunearpcache, tags: "tunearpcache"}
    - { role: ip_forwarding, tags: "ip_forwarding"}
    - { role: iptables, tags: "iptables", when: ffrl_tun is defined }
    - { role: backbone_gre_ffrl, tags: "backbone_gre_ffrl"}
    - { role: backbone_gre_ffms, tags: "backbone_gre_ffms"}
    - { role: gateways_gre, tags: "gateways_gre"}
    - { role: gateways_batman, tags: "gateways_batman"}
    - { role: gateways_gretap, tags: "gateways_gretap"}
    - { role: gateways_l2tp, tags: "gateways_l2tp"}
    - { role: bird, tags: "bird"}
    - { role: gateways_dhcp, tags: "gateways_dhcp"}
    - { role: gateways_bind, tags: "gateways_bind"}
    - { role: collectd, tags: "collectd"}
    - { role: set_kernel_param_maxcpus, tags: "set_kernel_param_maxcpus"}
