# Playbook zur Konfiguration aller Servern von services

- hosts: mapserver
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: backports-kernel, tags: "backports-kernel"}
    - { role: tunearpcache, tags: "tunearpcache"}
    - { role: services_interfaces, tags: "services_interfaces"}
    - { role: mapserver_hopglass-server, tags: "mapserver_hopglass-server"}
    - { role: mapserver_hopglass, tags: "mapserver_hopglass"}
    - { role: mapserver_nginx, tags: "mapserver_nginx"}
    - { role: collectd, tags: "collectd"}
    - { role: py_respondd, tags: "py_respondd"}
    - { role: mapserver_stats, tags: "mapserver_stats"}

