---
- hosts: monitoring
  vars_files:
    - passwords.yml
  remote_user: root
  roles:
    - { role: hostname, tags: "hostname"}
    - { role: common, tags: "common"}
    - { role: motd, tags: "motd"}
    - { role: unattended_upgrades, tags: "unattended_upgrades"}
