---
- name: reload systemd
  shell: systemctl daemon-reload 
   
- name: restart carbon-cache
  service: name=carbon-cache state=restarted

- name: restart uwsgi
  service: name=uwsgi state=restarted
    