---

- name: add docker repo
  apt_repository:
    repo: "deb http://apt.dockerproject.org/repo debian-jessie main"
    state: present

- name: add docker repo key
  apt_key:
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D

- name: install packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - docker-engine
    - python 
    - python-pip

- name: install docker-py
  pip: 
    name: docker-py 	
    state: latest
