
- name: Abhängigkeiten von alfred-json installieren
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - libjansson-dev
    - zlib1g-dev
    - cmake
    - git

- name: git für alfred-json
  git: repo=https://github.com/FreiFunkMuenster/alfred-json.git dest=/usr/src/alfred-json version=32922616e7aff4616a255d5e6a2931d68fe2d394

- stat: path=/usr/local/bin/alfred-json
  register: alfred_json

- name: alfred-json bauen
  shell: "mkdir -p build && cd build && cmake ../ && make && checkinstall -y make install"
  args:
    chdir: /usr/src/alfred-json
  notify:
  when: alfred_json.stat.exists == False
    
