---
- name: restart carbon-cache-instances
  service: name="carbon-cache@{{item.name}}.service" state=restarted
  with_items:
   - "{{graphite.cache_instances}}"

- name: restart carbon-relay
  service: name="carbon-relay" state=restarted

- name: restart uwsgi
  service: name=uwsgi.service state=restarted
