- name: Install dependencies
  apt:
    pkg: "{{item}}"
    state: installed
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - python-virtualenv 
    - libssl-dev
    - openssl
    - libacl1-dev
    - libacl1
    - liblz4-dev
    - liblz4-1
    - build-essential

- name: Install borgbackup
  pip: 
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items:
    - "borgbackup==1.0.10"
